In [2]:
import numpy as np
import pandas as pd

In [3]:
icd_codes = pd.read_csv("/cellar/users/mpagadal/data/ukbb/phenotypes/icd.df.melt.tsv", delimiter="\t")
icd_codes = icd_codes.rename(columns={"f.eid":"FID_Salem"})
icd_codes

        FID_Salem cancer ICD10  age of diagnosis      instance  age_instance
0         3797251         C449              46.9   f.40006.0.0   f.40008.0.0
1         1739424         C442              68.8   f.40006.0.0   f.40008.0.0
2         2233054         D000              54.9   f.40006.0.0   f.40008.0.0
3         2388047         D075              65.7   f.40006.0.0   f.40008.0.0
4         1384111         C443              60.0   f.40006.0.0   f.40008.0.0
...           ...          ...               ...           ...           ...
103461    3322894         C435              69.2  f.40006.10.0  f.40008.10.0
103462    5286408          C20              68.0  f.40006.11.0  f.40008.11.0
103463    5439697         C509              57.4  f.40006.13.0  f.40008.13.0
103464    5439697         C433              74.3  f.40006.15.0  f.40008.15.0
103465    5439697         D034              74.3  f.40006.16.0  f.40008.16.0

[103466 rows x 5 columns]

In [4]:
map_files = pd.read_csv("/cellar/users/mpagadal/data/ukbb/mapping/UKBiobank_Salem_shared_ID_mapping_file.txt", delim_whitespace=True)
map_files

            FID      IID  FID_Salem  IID_Salem
0       5309711  5309711    5768778    5768778
1       5607583  5607583    3066721    3066721
2       3534526  3534526    4324023    4324023
3       5138852  5138852    1595987    1595987
4       2187179  2187179    1530725    1530725
...         ...      ...        ...        ...
488372  3387495  3387495    4423134    4423134
488373  1801702  1801702    4086953    4086953
488374  4639336  4639336    5434784    5434784
488375  2621795  2621795    3252140    3252140
488376  5235209  5235209    1592606    1592606

[488377 rows x 4 columns]

In [5]:
pheno = pd.merge(icd_codes, map_files, on="FID_Salem")
del pheno["instance"]
del pheno["age_instance"]
del pheno["IID"]
pheno

        FID_Salem cancer ICD10  age of diagnosis      FID  IID_Salem
0         3797251         C449              46.9  1829897    3797251
1         1739424         C442              68.8  4654961    1739424
2         2233054         D000              54.9  2367012    2233054
3         2388047         D075              65.7  3667453    2388047
4         2388047          C61              66.5  3667453    2388047
...           ...          ...               ...      ...        ...
100037    5439697         D033              68.5  2351148    5439697
100038    5439697         C443              68.0  2351148    5439697
100039    5439697         C509              57.4  2351148    5439697
100040    5439697         C433              74.3  2351148    5439697
100041    5439697         D034              74.3  2351148    5439697

[100042 rows x 5 columns]

In [6]:
genotypes = pd.read_csv("/cellar/users/mpagadal/projects/tad-meqtl/data/dosage/ukbb.tad.meqtl.raw", delim_whitespace=True)
genotypes

,FID,IID,PAT,MAT,SEX,PHENOTYPE,10:3176243:C:T_T,10:72723176:G:A_A,10:88486374:A:G_G,10:88496902:G:A_A,...,9:34981981:C:G_G,9:35002131:C:G_G,9:35014767:G:A_A,9:35020923:G:C_G,9:35027139:A:G_G,9:35077441:T:C_T,9:80145512:C:A_C,9:94988863:G:T_T,9:95359093:C:G_G,9:136747832:T:C_C
0,5309711,5309711,0,0,1,-9,0.0,1.0,0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0
1,5607583,5607583,0,0,2,-9,1.0,0.0,0,0.0,...,1.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,1
2,3534526,3534526,0,0,2,-9,0.0,0.0,0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0
3,5138852,5138852,0,0,2,-9,0.0,0.0,0,0.0,...,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0
4,2187179,2187179,0,0,2,-9,0.0,1.0,0,0.0,...,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487404,3387495,3387495,0,0,2,-9,1.0,1.0,0,0.0,...,2.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0
487405,1801702,1801702,0,0,2,-9,0.0,1.0,0,1.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0
487406,4639336,4639336,0,0,1,-9,0.0,0.0,0,0.0,...,1.0,0.0,NaN,1.0,NaN,0.0,1.0,0.0,0.0,1
487407,2621795,2621795,0,0,2,-9,1.0,0.0,0,0.0,...,0.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,1
487408,5235209,5235209,0,0,1,-9,0.0,0.0,0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1

In [7]:
genotypes = genotypes.dropna()
genotypes = genotypes.reset_index(drop=True)
genotypes

,FID,IID,PAT,MAT,SEX,PHENOTYPE,10:3176243:C:T_T,10:72723176:G:A_A,10:88486374:A:G_G,10:88496902:G:A_A,...,9:34981981:C:G_G,9:35002131:C:G_G,9:35014767:G:A_A,9:35020923:G:C_G,9:35027139:A:G_G,9:35077441:T:C_T,9:80145512:C:A_C,9:94988863:G:T_T,9:95359093:C:G_G,9:136747832:T:C_C
0,1236218,1236218,0,0,1,-9,0.0,0.0,0,0.0,...,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1
1,2139308,2139308,0,0,2,-9,0.0,0.0,0,0.0,...,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0
2,5227851,5227851,0,0,2,-9,0.0,0.0,0,0.0,...,2.0,0.0,0.0,2.0,0.0,2.0,1.0,0.0,0.0,0
3,5702512,5702512,0,0,1,-9,0.0,0.0,0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0
4,2531123,2531123,0,0,1,-9,0.0,1.0,0,1.0,...,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12973,1890003,1890003,0,0,2,-9,1.0,0.0,0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0
12974,2269027,2269027,0,0,2,-9,0.0,0.0,1,0.0,...,0.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0
12975,4087344,4087344,0,0,2,-9,0.0,0.0,0,0.0,...,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0
12976,5135918,5135918,0,0,2,-9,0.0,0.0,0,0.0,...,2.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0
12977,5683783,5683783,0,0,1,-9,1.0,1.0,0,0.0,...,2.0,0.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0

In [8]:
combined = pd.merge(pheno, genotypes, on="FID")
combined

,FID_Salem,cancer ICD10,age of diagnosis,FID,IID_Salem,IID,PAT,MAT,SEX,PHENOTYPE,...,9:34981981:C:G_G,9:35002131:C:G_G,9:35014767:G:A_A,9:35020923:G:C_G,9:35027139:A:G_G,9:35077441:T:C_T,9:80145512:C:A_C,9:94988863:G:T_T,9:95359093:C:G_G,9:136747832:T:C_C
0,5067976,C509,47.8,2768145,5067976,2768145,0,0,2,-9,...,2.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,1
1,5067976,C433,54.7,2768145,5067976,2768145,0,0,2,-9,...,2.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,1
2,3594544,C437,50.6,2118009,3594544,2118009,0,0,2,-9,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,5028777,D046,63.2,4614193,5028777,4614193,0,0,2,-9,...,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0
4,4683442,D090,62.2,5524405,4683442,5524405,0,0,1,-9,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2670,2362357,C73,64.5,1772330,2362357,1772330,0,0,2,-9,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0
2671,3689926,C443,71.3,1245852,3689926,1245852,0,0,2,-9,...,2.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,2
2672,1878679,C64,72.0,2371131,1878679,2371131,0,0,2,-9,...,0.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0
2673,5501565,C509,52.2,3359556,5501565,3359556,0,0,2,-9,...,0.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0
2674,2890778,C001,66.3,3465684,2890778,3465684,0,0,1,-9,...,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1

In [9]:
print(len(pd.unique(combined["FID_Salem"])))

2216

In [10]:
labels = []
for i, row in combined.iterrows():
    if row["cancer ICD10"][0] == "C":
        labels.append(1)
    else:
        labels.append(0)
combined["Labels"] = labels
combined

,FID_Salem,cancer ICD10,age of diagnosis,FID,IID_Salem,IID,PAT,MAT,SEX,PHENOTYPE,...,9:35002131:C:G_G,9:35014767:G:A_A,9:35020923:G:C_G,9:35027139:A:G_G,9:35077441:T:C_T,9:80145512:C:A_C,9:94988863:G:T_T,9:95359093:C:G_G,9:136747832:T:C_C,Labels
0,5067976,C509,47.8,2768145,5067976,2768145,0,0,2,-9,...,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,1,1
1,5067976,C433,54.7,2768145,5067976,2768145,0,0,2,-9,...,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,1,1
2,3594544,C437,50.6,2118009,3594544,2118009,0,0,2,-9,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
3,5028777,D046,63.2,4614193,5028777,4614193,0,0,2,-9,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
4,4683442,D090,62.2,5524405,4683442,5524405,0,0,1,-9,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2670,2362357,C73,64.5,1772330,2362357,1772330,0,0,2,-9,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0,1
2671,3689926,C443,71.3,1245852,3689926,1245852,0,0,2,-9,...,0.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,2,1
2672,1878679,C64,72.0,2371131,1878679,2371131,0,0,2,-9,...,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0,1
2673,5501565,C509,52.2,3359556,5501565,3359556,0,0,2,-9,...,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0,1
2674,2890778,C001,66.3,3465684,2890778,3465684,0,0,1,-9,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1,1

In [43]:
combined.to_csv("risk_cancer_meqtl.csv")

In [11]:
icd_codes_cancer = icd_codes[icd_codes["cancer ICD10"].str.startswith("C")]
icd_codes_cancer["cancer ICD10"].value_counts()

C61     10077
C449     9529
C509     7622
C443     6808
C504     4173
        ...
C850        1
C104        1
C118        1
C631        1
C630        1
Name: cancer ICD10, Length: 402, dtype: int64

In [12]:
print(len(pd.unique(icd_codes_cancer["cancer ICD10"])))

402

In [17]:
snps = []
for col in combined:
    if ":" in col:
        l = col.split(":")
        last = l[-1].split("_")
        snps.append(l[0]+":"+l[1]+":"+l[2]+":"+last[0])
        snps.append(l[0]+":"+l[1]+":"+last[0]+":"+l[2])
snps

['10:3176243:C:T',
 '10:3176243:T:C',
 '10:72723176:G:A',
 '10:72723176:A:G',
 '10:88486374:A:G',
 '10:88486374:G:A',
 '10:88496902:G:A',
 '10:88496902:A:G',
 '10:88641501:A:T',
 '10:88641501:T:A',
 '10:104306160:G:T',
 '10:104306160:T:G',
 '10:104328719:A:C',
 '10:104328719:C:A',
 '10:104342804:G:A',
 '10:104342804:A:G',
 '10:130752146:A:G',
 '10:130752146:G:A',
 '10:131482653:C:T',
 '10:131482653:T:C',
 '11:22605592:C:T',
 '11:22605592:T:C',
 '11:22684540:G:A',
 '11:22684540:A:G',
 '11:23034213:T:C',
 '11:23034213:C:T',
 '11:23220093:T:G',
 '11:23220093:G:T',
 '11:46722221:T:C',
 '11:46722221:C:T',
 '11:46728952:G:C',
 '11:46728952:C:G',
 '11:46768041:A:G',
 '11:46768041:G:A',
 '11:46852839:A:G',
 '11:46852839:G:A',
 '11:46975125:T:C',
 '11:46975125:C:T',
 '11:47236405:C:G',
 '11:47236405:G:C',
 '11:117800481:G:C',
 '11:117800481:C:G',
 '11:119083318:A:C',
 '11:119083318:C:A',
 '11:128115740:T:C',
 '11:128115740:C:T',
 '12:13043119:C:T',
 '12:13043119:T:C',
 '12:22992541:C:A',
 '12:22992541:A:C',
 '12:25143390:A:T',
 '12:25143390:T:A',
 '12:25497964:G:A',
 '12:25497964:A:G',
 '12:25837689:C:G',
 '12:25837689:G:C',
 '12:57298771:G:C',
 '12:57298771:C:G',
 '12:70927023:A:G',
 '12:70927023:G:A',
 '12:95105784:G:A',
 '12:95105784:A:G',
 '12:95950002:A:T',
 '12:95950002:T:A',
 '12:95954955:G:A',
 '12:95954955:A:G',
 '12:95964031:C:A',
 '12:95964031:A:C',
 '12:114309389:C:A',
 '12:114309389:A:C',
 '12:116063437:T:A',
 '12:116063437:A:T',
 '13:33824988:T:C',
 '13:33824988:C:T',
 '13:33832610:G:A',
 '13:33832610:A:G',
 '13:48417877:T:C',
 '13:48417877:C:T',
 '13:91463947:G:C',
 '13:91463947:C:G',
 '13:94839689:T:C',
 '13:94839689:C:T',
 '13:95136055:G:T',
 '13:95136055:T:G',
 '14:81416170:A:G',
 '14:81416170:G:A',
 '14:105109483:C:G',
 '14:105109483:G:C',
 '14:105261414:G:C',
 '14:105261414:C:G',
 '15:40453075:G:A',
 '15:40453075:A:G',
 '15:50718276:T:C',
 '15:50718276:C:T',
 '15:50763627:A:G',
 '15:50763627:G:A',
 '15:50968906:A:C',
 '15:50968906:C:A',
 '15:50971539:C:A',
 '15:50971539:A:C',
 '15:51061227:A:C',
 '15:51061227:C:A',
 '15:51298925:C:T',
 '15:51298925:T:C',
 '15:51428197:A:T',
 '15:51428197:T:A',
 '15:66630569:G:A',
 '15:66630569:A:G',
 '15:66811952:C:T',
 '15:66811952:T:C',
 '15:68194099:A:G',
 '15:68194099:G:A',
 '15:91443059:T:C',
 '15:91443059:C:T',
 '16:374617:C:T',
 '16:374617:T:C',
 '16:10054912:A:G',
 '16:10054912:G:A',
 '16:10283486:C:T',
 '16:10283486:T:C',
 '16:11016508:G:A',
 '16:11016508:A:G',
 '16:68814826:G:A',
 '16:68814826:A:G',
 '16:72304915:C:T',
 '16:72304915:T:C',
 '16:74180094:C:G',
 '16:74180094:G:C',
 '16:74280696:T:C',
 '16:74280696:C:T',
 '16:74384296:C:T',
 '16:74384296:T:C',
 '16:74479071:A:G',
 '16:74479071:G:A',
 '16:74503258:G:C',
 '16:74503258:C:G',
 '16:74526649:G:A',
 '16:74526649:A:G',
 '16:74552127:C:T',
 '16:74552127:T:C',
 '16:74625065:C:A',
 '16:74625065:A:C',
 '16:74679883:C:T',
 '16:74679883:T:C',
 '16:74714604:C:T',
 '16:74714604:T:C',
 '16:74723707:G:A',
 '16:74723707:A:G',
 '16:89818340:G:C',
 '16:89818340:C:G',
 '16:89828862:T:C',
 '16:89828862:C:T',
 '16:89844043:T:C',
 '16:89844043:C:T',
 '16:89850415:C:G',
 '16:89850415:G:C',
 '16:89884502:C:T',
 '16:89884502:T:C',
 '16:90038786:C:A',
 '16:90038786:A:C',
 '16:90111833:C:T',
 '16:90111833:T:C',
 '16:90115731:G:A',
 '16:90115731:A:G',
 '16:90133137:G:T',
 '16:90133137:T:G',
 '17:47770417:C:G',
 '17:47770417:G:C',
 '17:59444758:G:A',
 '17:59444758:A:G',
 '19:40347035:G:A',
 '19:40347035:A:G',
 '19:45825626:A:T',
 '19:45825626:T:A',
 '19:45868478:T:A',
 '19:45868478:A:T',
 '19:45878605:C:T',
 '19:45878605:T:C',
 '19:45912406:G:A',
 '19:45912406:A:G',
 '19:45923653:A:G',
 '19:45923653:G:A',
 '19:45979037:G:C',
 '19:45979037:C:G',
 '19:50148052:G:A',
 '19:50148052:A:G',
 '19:52685944:C:A',
 '19:52685944:A:C',
 '19:52701643:T:C',
 '19:52701643:C:T',
 '19:52706991:T:C',
 '19:52706991:C:T',
 '19:52726161:C:T',
 '19:52726161:T:C',
 '1:11655410:A:C',
 '1:11655410:C:A',
 '1:14901093:A:G',
 '1:14901093:G:A',
 '1:15817090:C:T',
 '1:15817090:T:C',
 '1:15914135:A:G',
 '1:15914135:G:A',
 '1:17403405:G:T',
 '1:17403405:T:G',
 '1:18144014:T:C',
 '1:18144014:C:T',
 '1:18241271:G:C',
 '1:18241271:C:G',
 '1:18247811:G:T',
 '1:18247811:T:G',
 '1:18273842:T:G',
 '1:18273842:G:T',
 '1:18774941:T:A',
 '1:18774941:A:T',
 '1:52056757:A:T',
 '1:52056757:T:A',
 '1:77788462:C:G',
 '1:77788462:G:C',
 '1:77994269:C:T',
 '1:77994269:T:C',
 '1:93082190:A:G',
 '1:93082190:G:A',
 '1:116094437:A:G',
 '1:116094437:G:A',
 '1:117656276:A:G',
 '1:117656276:G:A',
 '1:150913257:C:T',
 '1:150913257:T:C',
 '1:150980281:T:C',
 '1:150980281:C:T',
 '1:151734690:G:C',
 '1:151734690:C:G',
 '1:163436669:G:T',
 '1:163436669:T:G',
 '1:241428657:G:A',
 '1:241428657:A:G',
 '1:243647208:G:T',
 '1:243647208:T:G',
 '1:243662027:T:C',
 '1:243662027:C:T',
 '1:243672074:C:T',
 '1:243672074:T:C',
 '1:243822570:T:C',
 '1:243822570:C:T',
 '1:243889364:A:G',
 '1:243889364:G:A',
 '1:243923452:C:T',
 '1:243923452:T:C',
 '20:35946239:G:A',
 '20:35946239:A:G',
 '20:41323288:T:C',
 '20:41323288:C:T',
 '20:50392521:A:G',
 '20:50392521:G:A',
 '20:50431113:C:T',
 '20:50431113:T:C',
 '20:56648906:G:A',
 '20:56648906:A:G',
 '20:56705336:G:C',
 '20:56705336:C:G',
 '20:57375308:T:C',
 '20:57375308:C:T',
 '20:57469073:T:C',
 '20:57469073:C:T',
 '20:57852805:C:T',
 '20:57852805:T:C',
 '20:58286790:C:T',
 '20:58286790:T:C',
 '20:58315732:T:C',
 '20:58315732:C:T',
 '20:58353666:A:G',
 '20:58353666:G:A',
 '20:58409943:C:T',
 '20:58409943:T:C',
 '22:20046042:A:G',
 '22:20046042:G:A',
 '22:22554306:T:C',
 '22:22554306:C:T',
 '22:24138301:C:T',
 '22:24138301:T:C',
 '22:24146560:C:T',
 '22:24146560:T:C',
 '22:24157537:T:C',
 '22:24157537:C:T',
 '22:24158899:C:A',
 '22:24158899:A:C',
 '22:24166256:G:C',
 '22:24166256:C:G',
 '22:24168998:A:G',
 '22:24168998:G:A',
 '22:29960768:T:G',
 '22:29960768:G:T',
 '22:30097258:G:C',
 '22:30097258:C:G',
 '22:30509399:T:C',
 '22:30509399:C:T',
 '2:16696775:G:A',
 '2:16696775:A:G',
 '2:16880977:G:A',
 '2:16880977:A:G',
 '2:24692809:C:G',
 '2:24692809:G:C',
 '2:25229434:T:A',
 '2:25229434:A:T',
 '2:26562616:T:C',
 '2:26562616:C:T',
 '2:44246726:C:G',
 '2:44246726:G:C',
 '2:47652455:C:T',
 '2:47652455:T:C',
 '2:47736061:C:G',
 '2:47736061:G:C',
 '2:47785260:T:C',
 '2:47785260:C:T',
 '2:60889037:G:C',
 '2:60889037:C:G',
 '2:137043076:G:A',
 '2:137043076:A:G',
 '2:142672805:T:C',
 '2:142672805:C:T',
 '2:142821525:T:A',
 '2:142821525:A:T',
 '2:142864800:G:T',
 '2:142864800:T:G',
 '2:142890187:G:C',
 '2:142890187:C:G',
 '2:142909392:A:C',
 '2:142909392:C:A',
 '2:159402671:G:A',
 '2:159402671:A:G',
 '2:178087387:T:C',
 '2:178087387:C:T',
 '2:178145692:G:A',
 '2:178145692:A:G',
 '2:201132135:A:G',
 '2:201132135:G:A',
 '2:201245872:A:G',
 '2:201245872:G:A',
 '2:202143928:T:C',
 '2:202143928:C:T',
 '2:209220238:G:C',
 '2:209220238:C:G',
 '2:209239899:T:C',
 '2:209239899:C:T',
 '2:209240247:T:C',
 '2:209240247:C:T',
 '2:209295636:T:C',
 '2:209295636:C:T',
 '2:209350308:A:G',
 '2:209350308:G:A',
 '2:209428914:G:A',
 '2:209428914:A:G',
 '2:209466517:G:A',
 '2:209466517:A:G',
 '2:213046616:C:T',
 '2:213046616:T:C',
 '2:213151472:G:A',
 '2:213151472:A:G',
 '2:213169514:T:C',
 '2:213169514:C:T',
 '2:213210229:C:T',
 '2:213210229:T:C',
 '2:213211112:G:A',
 '2:213211112:A:G',
 '2:213240767:T:C',
 '2:213240767:C:T',
 '2:213248130:G:A',
 '2:213248130:A:G',
 '2:213253561:T:A',
 '2:213253561:A:T',
 '2:213275113:A:G',
 '2:213275113:G:A',
 '2:213294557:C:T',
 '2:213294557:T:C',
 '2:213317329:C:T',
 '2:213317329:T:C',
 '2:213328348:G:A',
 '2:213328348:A:G',
 '2:213353139:T:C',
 '2:213353139:C:T',
 '2:213354898:C:T',
 '2:213354898:T:C',
 '2:213389346:A:G',
 '2:213389346:G:A',
 '2:213403863:C:T',
 '2:213403863:T:C',
 '2:213409719:G:A',
 '2:213409719:A:G',
 '2:213412426:T:A',
 '2:213412426:A:T',
 '2:213412426:T:C',
 '2:213412426:C:T',
 '2:213423503:C:T',
 '2:213423503:T:C',
 '2:213432392:G:A',
 '2:213432392:A:G',
 '2:213468449:C:T',
 '2:213468449:T:C',
 '2:213492540:A:G',
 '2:213492540:G:A',
 '2:213542405:C:T',
 '2:213542405:T:C',
 '2:215840829:A:G',
 '2:215840829:G:A',
 '3:13585313:T:C',
 '3:13585313:C:T',
 '3:13603323:C:G',
 '3:13603323:G:C',
 '3:14558157:G:C',
 '3:14558157:C:G',
 '3:30850476:C:T',
 '3:30850476:T:C',
 '3:53766284:G:A',
 '3:53766284:A:G',
 '3:70069621:T:A',
 '3:70069621:A:T',
 '3:76310156:C:T',
 '3:76310156:T:C',
 '3:105572625:A:C',
 '3:105572625:C:A',
 '3:121123223:G:A',
 '3:121123223:A:G',
 '3:127481508:G:C',
 '3:127481508:C:G',
 '3:141889009:T:G',
 '3:141889009:G:T',
 '3:185903412:G:C',
 '3:185903412:C:G',
 '3:189346815:C:G',
 '3:189346815:G:C',
 '3:194674114:A:C',
 '3:194674114:C:A',
 '4:106067592:G:T',
 '4:106067592:T:G',
 '4:106074826:T:G',
 '4:106074826:G:T',
 '5:56040770:A:C',
 '5:56040770:C:A',
 '5:56085225:C:T',
 '5:56085225:T:C',
 '5:56130322:T:C',
 '5:56130322:C:T',
 '5:56279030:G:A',
 '5:56279030:A:G',
 '5:111685750:T:C',
 '5:111685750:C:T',
 '5:112035318:A:T',
 '5:112035318:T:A',
 '5:112139424:A:G',
 '5:112139424:G:A',
 '5:112179909:C:A',
 '5:112179909:A:C',
 '5:180055188:A:G',
 '5:180055188:G:A',
 '5:180060804:G:C',
 '5:180060804:C:G',
 '5:180070297:G:A',
 '5:180070297:A:G',
 '5:180079923:C:T',
 '5:180079923:T:C',
 '6:35676991:A:G',
 '6:35676991:G:A',
 '6:99925443:C:T',
 '6:99925443:T:C',
 '6:99984803:A:G',
 '6:99984803:G:A',
 '6:100025000:C:T',
 '6:100025000:T:C',
 '6:100046473:A:G',
 '6:100046473:G:A',
 '6:106006902:C:T',
 '6:106006902:T:C',
 '6:133677340:A:T',
 '6:133677340:T:A',
 '6:134627425:A:G',
 '6:134627425:G:A',
 '6:149811693:A:G',
 '6:149811693:G:A',
 '6:150761290:G:A',
 '6:150761290:A:G',
 '6:150761290:G:T',
 '6:150761290:T:G',
 '6:156942543:T:G',
 '6:156942543:G:T',
 '6:164338015:T:A',
 '6:164338015:A:T',
 '7:5584599:G:A',
 '7:5584599:A:G',
 '7:37950115:C:T',
 '7:37950115:T:C',
 '7:116895577:G:A',
 '7:116895577:A:G',
 '7:125171800:G:C',
 '7:125171800:C:G',
 '7:145990449:A:G',
 '7:145990449:G:A',
 '8:29902641:C:T',
 '8:29902641:T:C',
 '8:29982518:T:C',
 '8:29982518:C:T',
 '8:41976334:G:A',
 '8:41976334:A:G',
 '8:41976334:G:C',
 '8:41976334:C:G',
 '8:90126767:C:G',
 '8:90126767:G:C',
 '8:113866149:A:G',
 '8:113866149:G:A',
 '9:8846218:C:T',
 '9:8846218:T:C',
 '9:8847950:C:T',
 '9:8847950:T:C',
 '9:8849238:T:C',
 '9:8849238:C:T',
 '9:8851845:T:C',
 '9:8851845:C:T',
 '9:8862724:C:G',
 '9:8862724:G:C',
 '9:8871342:G:C',
 '9:8871342:C:G',
 '9:10389328:C:G',
 '9:10389328:G:C',
 '9:21986218:C:T',
 '9:21986218:T:C',
 '9:22005330:T:G',
 '9:22005330:G:T',
 '9:22293346:T:C',
 '9:22293346:C:T',
 '9:34981981:C:G',
 '9:34981981:G:C',
 '9:35002131:C:G',
 '9:35002131:G:C',
 '9:35014767:G:A',
 '9:35014767:A:G',
 '9:35020923:G:C',
 '9:35020923:C:G',
 '9:35027139:A:G',
 '9:35027139:G:A',
 '9:35077441:T:C',
 '9:35077441:C:T',
 '9:80145512:C:A',
 '9:80145512:A:C',
 '9:94988863:G:T',
 '9:94988863:T:G',
 '9:95359093:C:G',
 '9:95359093:G:C',
 '9:136747832:T:C',
 '9:136747832:C:T']

In [18]:
risk_snps = pd.DataFrame()
risk_snps["SNP"] = snps
risk_snps

                 SNP
0     10:3176243:C:T
1     10:3176243:T:C
2    10:72723176:G:A
3    10:72723176:A:G
4    10:88486374:A:G
..               ...
543   9:94988863:T:G
544   9:95359093:C:G
545   9:95359093:G:C
546  9:136747832:T:C
547  9:136747832:C:T

[548 rows x 1 columns]

In [15]:
meqtls = pd.read_csv("meqtls_tads.csv")
meqtls_short = pd.DataFrame()
meqtls_short["SNP"] = meqtls["SNP"]
meqtls_short["TAD_Type"] = meqtls["TAD Type"]
meqtls

,Unnamed: 0,num,cancer_type,rsid,snp_position,alleles,probes,probe_position,probe_gene,beta,status,r,p-value,cancer,chr,bp,SNP,TAD Type
0,0,0,BLCA,rs11684598,chr2:33952621,G/A,cg04131969,chr2:33951647,MYADML,-1.24,-40.26,-0.90,3.940000e-139,BLCA,chr2,33952621,2:33952621:G:A,Boundary
1,1,1,BLCA,rs12232965,chr2:33954560,C/T,cg04131969,chr2:33951647,MYADML,-1.24,-39.59,-0.90,6.710000e-137,BLCA,chr2,33954560,2:33954560:C:T,Boundary
2,2,2,BLCA,rs7574695,chr2:33953186,C/T,cg04131969,chr2:33951647,MYADML,-1.24,-39.35,-0.90,4.230000e-136,BLCA,chr2,33953186,2:33953186:C:T,Boundary
3,3,3,BLCA,rs11777332,chr8:91676709,G/A,cg16814680,chr8:91681699,NaN,-1.20,-36.65,-0.88,8.170000e-127,BLCA,chr8,91676709,8:91676709:G:A,Boundary
4,4,4,BLCA,rs4332092,chr8:91677926,G/A,cg16814680,chr8:91681699,NaN,-1.20,-36.65,-0.88,8.170000e-127,BLCA,chr8,91677926,8:91677926:G:A,Boundary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1236137,1236137,1236137,UCEC,rs60260871,chr3:124711371,C/T,cg11029367,chr3:124705145,HEG1,0.43,4.58,0.35,9.990000e-06,UCEC,chr3,124711371,3:124711371:C:T,Boundary
1236138,1236138,1236138,UCEC,rs57574713,chr3:124711386,G/A,cg11029367,chr3:124705145,HEG1,0.43,4.58,0.35,9.990000e-06,UCEC,chr3,124711386,3:124711386:G:A,Boundary
1236139,1236139,1236139,UCEC,rs10903612,chr10:2018353,C/T,cg16296438,chr10:1416569,ADARB2,0.36,4.58,0.35,9.990000e-06,UCEC,chr10,2018353,10:2018353:C:T,Neither
1236140,1236140,1236140,UCEC,rs4880953,chr10:2019373,C/T,cg16296438,chr10:1416569,ADARB2,0.36,4.58,0.35,9.990000e-06,UCEC,chr10,2019373,10:2019373:C:T,Neither
1236141,1236141,1236141,UCEC,rs11002432,chr10:79931884,C/T,cg15849445,chr10:80635973,NaN,0.58,4.58,0.35,9.990000e-06,UCEC,chr10,79931884,10:79931884:C:T,Boundary

In [19]:
risk_snps = pd.merge(risk_snps, meqtls_short, on="SNP")
risk_snps

                 SNP  TAD_Type
0     10:3176243:C:T   Neither
1    10:72723176:G:A  Inactive
2    10:88486374:A:G    Active
3    10:88496902:G:A    Active
4    10:88641501:A:T    Active
..               ...       ...
266   9:35077441:T:C  Inactive
267   9:80145512:C:A  Boundary
268   9:94988863:G:T  Boundary
269   9:95359093:C:G  Inactive
270  9:136747832:C:T    Active

[271 rows x 2 columns]

In [20]:
risk_snps["TAD_Type"].value_counts()

Boundary    187
Inactive     39
Active       21
Neither      13
Mixed        11
Name: TAD_Type, dtype: int64

In [32]:
active_genotype = pd.DataFrame()
inactive_genotype = pd.DataFrame()
boundary_genotype = pd.DataFrame()
for col in genotypes:
    if (":" in col):
        l = col.split(":")
        last = l[-1].split("_")
        snp1 = l[0]+":"+l[1]+":"+l[2]+":"+last[0]
        snp2 = l[0]+":"+l[1]+":"+last[0]+":"+l[2]
        if snp1 in list(risk_snps[risk_snps["TAD_Type"] == "Active"]["SNP"]) or snp2 in list(risk_snps[risk_snps["TAD_Type"] == "Active"]["SNP"]):
            active_genotype[col] = genotypes[col]
        elif snp1 in list(risk_snps[risk_snps["TAD_Type"] == "Inactive"]["SNP"]) or snp2 in list(risk_snps[risk_snps["TAD_Type"] == "Inactive"]["SNP"]):
            inactive_genotype[col] = genotypes[col]
        elif snp1 in list(risk_snps[risk_snps["TAD_Type"] == "Boundary"]["SNP"]) or snp2 in list(risk_snps[risk_snps["TAD_Type"] == "Boundary"]["SNP"]):
            boundary_genotype[col] = genotypes[col]
    else:
        active_genotype[col] = genotypes[col]
        inactive_genotype[col] = genotypes[col]
        boundary_genotype[col] = genotypes[col]

In [35]:
active_genotype

,FID,IID,PAT,MAT,SEX,PHENOTYPE,10:88486374:A:G_G,10:88496902:G:A_A,10:88641501:A:T_T,11:119083318:A:C_C,...,16:74679883:C:T_T,16:89818340:G:C_C,16:89828862:T:C_C,16:89844043:T:C_C,16:89850415:C:G_G,16:89884502:C:T_C,1:15914135:A:G_G,1:150913257:C:T_T,7:5584599:G:A_A,9:136747832:T:C_C
0,1236218,1236218,0,0,1,-9,0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1
1,2139308,2139308,0,0,2,-9,0,0.0,0.0,0.0,...,0.0,1.0,2.0,1.0,0.0,0.0,0.0,1.0,1.0,0
2,5227851,5227851,0,0,2,-9,0,0.0,0.0,2.0,...,0.0,2.0,2.0,2.0,1.0,0.0,1.0,0.0,0.0,0
3,5702512,5702512,0,0,1,-9,0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0
4,2531123,2531123,0,0,1,-9,0,1.0,1.0,0.0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12973,1890003,1890003,0,0,2,-9,0,0.0,2.0,1.0,...,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0
12974,2269027,2269027,0,0,2,-9,1,0.0,1.0,0.0,...,0.0,2.0,2.0,2.0,1.0,0.0,0.0,0.0,1.0,0
12975,4087344,4087344,0,0,2,-9,0,0.0,0.0,0.0,...,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0
12976,5135918,5135918,0,0,2,-9,0,0.0,1.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0
12977,5683783,5683783,0,0,1,-9,0,0.0,0.0,1.0,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,0

In [36]:
active_genotype.to_csv("modeling_risk/risk_active.csv")
inactive_genotype.to_csv("modeling_risk/risk_inactive.csv")
boundary_genotype.to_csv("modeling_risk/risk_boundary.csv")

In [38]:
combined_active = pd.merge(pheno, active_genotype, on="FID")
labels = []
for i, row in combined_active.iterrows():
    if row["cancer ICD10"][0] == "C":
        labels.append(1)
    else:
        labels.append(0)
combined_active["Labels"] = labels
combined_active

,FID_Salem,cancer ICD10,age of diagnosis,FID,IID_Salem,IID,PAT,MAT,SEX,PHENOTYPE,...,16:89818340:G:C_C,16:89828862:T:C_C,16:89844043:T:C_C,16:89850415:C:G_G,16:89884502:C:T_C,1:15914135:A:G_G,1:150913257:C:T_T,7:5584599:G:A_A,9:136747832:T:C_C,Labels
0,5067976,C509,47.8,2768145,5067976,2768145,0,0,2,-9,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1,1
1,5067976,C433,54.7,2768145,5067976,2768145,0,0,2,-9,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1,1
2,3594544,C437,50.6,2118009,3594544,2118009,0,0,2,-9,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1,1
3,5028777,D046,63.2,4614193,5028777,4614193,0,0,2,-9,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0,0
4,4683442,D090,62.2,5524405,4683442,5524405,0,0,1,-9,...,2.0,2.0,1.0,1.0,0.0,0.0,0.0,1.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2670,2362357,C73,64.5,1772330,2362357,1772330,0,0,2,-9,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
2671,3689926,C443,71.3,1245852,3689926,1245852,0,0,2,-9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2,1
2672,1878679,C64,72.0,2371131,1878679,2371131,0,0,2,-9,...,2.0,2.0,2.0,2.0,0.0,1.0,1.0,2.0,0,1
2673,5501565,C509,52.2,3359556,5501565,3359556,0,0,2,-9,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0,1
2674,2890778,C001,66.3,3465684,2890778,3465684,0,0,1,-9,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1,1

In [39]:
combined_inactive = pd.merge(pheno, inactive_genotype, on="FID")
labels = []
for i, row in combined_inactive.iterrows():
    if row["cancer ICD10"][0] == "C":
        labels.append(1)
    else:
        labels.append(0)
combined_inactive["Labels"] = labels
combined_inactive

,FID_Salem,cancer ICD10,age of diagnosis,FID,IID_Salem,IID,PAT,MAT,SEX,PHENOTYPE,...,6:150761290:G:T_T,7:116895577:G:A_A,9:34981981:C:G_G,9:35002131:C:G_G,9:35014767:G:A_A,9:35020923:G:C_G,9:35027139:A:G_G,9:35077441:T:C_T,9:95359093:C:G_G,Labels
0,5067976,C509,47.8,2768145,5067976,2768145,0,0,2,-9,...,1.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0,0.0,1
1,5067976,C433,54.7,2768145,5067976,2768145,0,0,2,-9,...,1.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0,0.0,1
2,3594544,C437,50.6,2118009,3594544,2118009,0,0,2,-9,...,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1
3,5028777,D046,63.2,4614193,5028777,4614193,0,0,2,-9,...,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0
4,4683442,D090,62.2,5524405,4683442,5524405,0,0,1,-9,...,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2670,2362357,C73,64.5,1772330,2362357,1772330,0,0,2,-9,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1
2671,3689926,C443,71.3,1245852,3689926,1245852,0,0,2,-9,...,2.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,0.0,1
2672,1878679,C64,72.0,2371131,1878679,2371131,0,0,2,-9,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1
2673,5501565,C509,52.2,3359556,5501565,3359556,0,0,2,-9,...,1.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1
2674,2890778,C001,66.3,3465684,2890778,3465684,0,0,1,-9,...,2.0,2.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1

In [40]:
combined_boundary = pd.merge(pheno, boundary_genotype, on="FID")
labels = []
for i, row in combined_boundary.iterrows():
    if row["cancer ICD10"][0] == "C":
        labels.append(1)
    else:
        labels.append(0)
combined_boundary["Labels"] = labels
combined_boundary

,FID_Salem,cancer ICD10,age of diagnosis,FID,IID_Salem,IID,PAT,MAT,SEX,PHENOTYPE,...,9:8851845:T:C_C,9:8862724:C:G_C,9:8871342:G:C_C,9:10389328:C:G_C,9:21986218:C:T_T,9:22005330:T:G_G,9:22293346:T:C_T,9:80145512:C:A_C,9:94988863:G:T_T,Labels
0,5067976,C509,47.8,2768145,5067976,2768145,0,0,2,-9,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,5067976,C433,54.7,2768145,5067976,2768145,0,0,2,-9,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,3594544,C437,50.6,2118009,3594544,2118009,0,0,2,-9,...,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,5028777,D046,63.2,4614193,5028777,4614193,0,0,2,-9,...,1.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0
4,4683442,D090,62.2,5524405,4683442,5524405,0,0,1,-9,...,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2670,2362357,C73,64.5,1772330,2362357,1772330,0,0,2,-9,...,1.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1
2671,3689926,C443,71.3,1245852,3689926,1245852,0,0,2,-9,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1
2672,1878679,C64,72.0,2371131,1878679,2371131,0,0,2,-9,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1
2673,5501565,C509,52.2,3359556,5501565,3359556,0,0,2,-9,...,1.0,2.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1
2674,2890778,C001,66.3,3465684,2890778,3465684,0,0,1,-9,...,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1

In [41]:
combined_active.to_csv("modeling_risk/icd10_risk_active_meqtls.csv")
combined_inactive.to_csv("modeling_risk/icd10_risk_inactive_meqtls.csv")
combined_boundary.to_csv("modeling_risk/icd10_risk_boundary_meqtls.csv")

In [3]:
data_active = pd.read_csv("modeling_risk/icd10_risk_active_meqtls.csv")
data_active

,Unnamed: 0,FID_Salem,cancer ICD10,age of diagnosis,FID,IID_Salem,IID,PAT,MAT,SEX,...,16:89818340:G:C_C,16:89828862:T:C_C,16:89844043:T:C_C,16:89850415:C:G_G,16:89884502:C:T_C,1:15914135:A:G_G,1:150913257:C:T_T,7:5584599:G:A_A,9:136747832:T:C_C,Labels
0,0,5067976,C509,47.8,2768145,5067976,2768145,0,0,2,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1,1
1,1,5067976,C433,54.7,2768145,5067976,2768145,0,0,2,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1,1
2,2,3594544,C437,50.6,2118009,3594544,2118009,0,0,2,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1,1
3,3,5028777,D046,63.2,4614193,5028777,4614193,0,0,2,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0,0
4,4,4683442,D090,62.2,5524405,4683442,5524405,0,0,1,...,2.0,2.0,1.0,1.0,0.0,0.0,0.0,1.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2670,2670,2362357,C73,64.5,1772330,2362357,1772330,0,0,2,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1
2671,2671,3689926,C443,71.3,1245852,3689926,1245852,0,0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2,1
2672,2672,1878679,C64,72.0,2371131,1878679,2371131,0,0,2,...,2.0,2.0,2.0,2.0,0.0,1.0,1.0,2.0,0,1
2673,2673,5501565,C509,52.2,3359556,5501565,3359556,0,0,2,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0,1
2674,2674,2890778,C001,66.3,3465684,2890778,3465684,0,0,1,...,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1,1